# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-22 22:45
from __future__ import unicode_literals

import account.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='age_range',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.'), account.models.validate_age_range]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='authenticator',
            field=models.CharField(default='local', max_length=25, validators=[account.models.validate_authenticator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='birthday_date',
            field=models.DateField(null=True, validators=[account.models.validate_birth_date]),
        ),
    ]
