# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 00:11
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170422_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='birthday_date',
            field=models.DateField(blank=True, null=True, validators=[account.models.validate_birth_date]),
        ),
    ]
