# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 02:32
from __future__ import unicode_literals

import account.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170423_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='age_range',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.'), account.models.validate_age_range]),
        ),
    ]
