# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-23 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usuario_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='birthday_date',
            new_name='birth_date',
        ),
    ]
