# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-14 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_usuario_picture_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='picture_url',
        ),
    ]
