# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-14 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_usuario_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='age_range',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
