# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('rating', models.IntegerField()),
                ('desc', models.CharField(max_length=300)),
                ('litrao', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Esportes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('rating', models.IntegerField()),
                ('desc', models.CharField(max_length=300)),
                ('modalidades', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Festa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('rating', models.IntegerField()),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Teatro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('rating', models.IntegerField()),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
