# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-21 21:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bar',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('bairro', models.CharField(default='', max_length=40)),
                ('endereco', models.CharField(default='', max_length=50)),
                ('mais_info', models.CharField(default='', help_text='Link para site/facebook/instagram/outros', max_length=100)),
                ('tipoDoEvento', models.CharField(choices=[('BA', 'Bar'), ('ES', 'Esporte'), ('FE', 'Festa'), ('TE', 'Teatro')], max_length=2)),
                ('dias_aberto', models.CharField(default='', max_length=50)),
                ('horario', models.CharField(default='', max_length=20)),
                ('media_cerveja', models.DecimalField(decimal_places=2, default='00,00', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('media_drinks', models.DecimalField(decimal_places=2, default='00,00', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('media_shots', models.DecimalField(decimal_places=2, default='00,00', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('media_petiscos', models.DecimalField(decimal_places=2, default='00,00', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='esporte',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('bairro', models.CharField(default='', max_length=40)),
                ('endereco', models.CharField(default='', max_length=50)),
                ('mais_info', models.CharField(default='', help_text='Link para site/facebook/instagram/outros', max_length=100)),
                ('tipoDoEvento', models.CharField(choices=[('BA', 'Bar'), ('ES', 'Esporte'), ('FE', 'Festa'), ('TE', 'Teatro')], max_length=2)),
                ('modalidade', models.CharField(default='', max_length=20)),
                ('jogos', models.CharField(default='', help_text='Insira os times participantes', max_length=100)),
                ('ingressos', models.CharField(default='', help_text='Masc/Fem/Unissex', max_length=50)),
                ('horario', models.CharField(default='', help_text='HH:MM', max_length=20)),
                ('dia', models.CharField(default='', help_text='DD/MM/AAAA', max_length=10)),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='festa',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('bairro', models.CharField(default='', max_length=40)),
                ('endereco', models.CharField(default='', max_length=50)),
                ('mais_info', models.CharField(default='', help_text='Link para site/facebook/instagram/outros', max_length=100)),
                ('tipoDoEvento', models.CharField(choices=[('BA', 'Bar'), ('ES', 'Esporte'), ('FE', 'Festa'), ('TE', 'Teatro')], max_length=2)),
                ('ingressos', models.CharField(default='', help_text='Masc/Fem/Unissex', max_length=50)),
                ('horario', models.CharField(default='', help_text='HH:MM', max_length=20)),
                ('dia', models.CharField(default='', help_text='DD/MM/AAAA', max_length=10)),
                ('atracoes', models.TextField(help_text='Escreva as atracoes com seus horarios')),
                ('classEtaria', models.CharField(default='', max_length=10)),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='teatro',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('bairro', models.CharField(default='', max_length=40)),
                ('endereco', models.CharField(default='', max_length=50)),
                ('mais_info', models.CharField(default='', help_text='Link para site/facebook/instagram/outros', max_length=100)),
                ('tipoDoEvento', models.CharField(choices=[('BA', 'Bar'), ('ES', 'Esporte'), ('FE', 'Festa'), ('TE', 'Teatro')], max_length=2)),
                ('ingressos', models.CharField(default='', help_text='Masc/Fem/Unissex', max_length=50)),
                ('horario', models.CharField(default='', help_text='HH:MM', max_length=20)),
                ('dia', models.CharField(default='', help_text='DD/MM/AAAA', max_length=10)),
                ('direcao', models.CharField(default='', max_length=20)),
                ('producao', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
    ]
