# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='precoLitrao',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
