# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-15 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Esportes',
        ),
        migrations.DeleteModel(
            name='Teatro',
        ),
    ]
