# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 02:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20170616_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar',
            name='precoLitrao',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
