# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20170616_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='esporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipoDoEvento', models.CharField(choices=[('BA', 'Bar'), ('ES', 'Esporte'), ('FE', 'Festa'), ('TE', 'Teatro')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='festa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipoDoEvento', models.CharField(choices=[('BA', 'Bar'), ('ES', 'Esporte'), ('FE', 'Festa'), ('TE', 'Teatro')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='teatro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipoDoEvento', models.CharField(choices=[('BA', 'Bar'), ('ES', 'Esporte'), ('FE', 'Festa'), ('TE', 'Teatro')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
