# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_esporte_festa_teatro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='esporte',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='festa',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='teatro',
            options={'ordering': ['nome']},
        ),
    ]
