# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-16 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20170616_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='id',
        ),
        migrations.RemoveField(
            model_name='esporte',
            name='id',
        ),
        migrations.RemoveField(
            model_name='festa',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teatro',
            name='id',
        ),
        migrations.AlterField(
            model_name='bar',
            name='nome',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='esporte',
            name='nome',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='festa',
            name='nome',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teatro',
            name='nome',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
