# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20170616_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='festa',
            name='nomeFesta',
            field=models.CharField(default='Nome da sua festa', max_length=50),
        ),
    ]
