# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_festa_nomefesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festa',
            name='nomeFesta',
        ),
        migrations.AddField(
            model_name='festa',
            name='atracoes',
            field=models.CharField(default='', max_length=50),
        ),
    ]
