# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-17 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_auto_20170617_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='festa',
            name='classEtaria',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='festa',
            name='dia',
            field=models.CharField(default='', help_text='DD/MM/AAAA', max_length=10),
        ),
        migrations.AddField(
            model_name='festa',
            name='horario',
            field=models.CharField(default='', help_text='HH:MM', max_length=20),
        ),
        migrations.AlterField(
            model_name='festa',
            name='atracoes',
            field=models.TextField(help_text='Escreva as atracoes com seus horarios'),
        ),
    ]
